Feature 70
RDaniil/lampbearer pull request #111
Opened 2024-07-17 13:18 UTC by RDaniil

2024-07-27 13:36 UTC, ch1-zha requested changes

2024-07-27 13:36 UTC, ch1-zha commented on game/src/main/java/com/vdn/lampbearer/attributes/AbstractInventoryAttr.java
> +    List<T> items = new ArrayList<>();
`private final`

2024-07-27 13:36 UTC, ch1-zha commented on game/src/main/java/com/vdn/lampbearer/action/reactions/LoadOneInFirearmReaction.java
> +        }
Непринципиально, но лично мне проще читать код с таким подходом, плюс вложенности меньше
```
if (!(foundFirearm.get() instanceof AbstractFirearm)) {
    return false;    
}

var firearm = (AbstractFirearm<?>) foundFirearm.get();
    //...
if (roundsLoaded > 0) {
    //...
}
```

2024-07-27 13:36 UTC, ch1-zha commented on game/src/main/java/com/vdn/lampbearer/action/reactions/ShootFirearmReaction.java
> +        if (foundFirearm.get() instanceof AbstractFirearm) {
При не выполнении условия разве не следует вернуть false? Может ли существовать оружие, которое не является наследнком AbstractFirearm?

2024-07-27 13:36 UTC, ch1-zha commented on game/src/main/java/com/vdn/lampbearer/attributes/AbstractInventoryAttr.java
> +    protected final int maxSize;
Кроме этого класса нигде не используется. Делаем private?

2024-07-27 13:36 UTC, ch1-zha commented on game/src/main/java/com/vdn/lampbearer/entites/item/firearm/AbstractFirearm.java
> +    public abstract int loadAllRounds(RoundContainerAttr ammoBox);
loadOneRound -> LoadOneInFirearm(Action|Reaction)
loadAllRounds -> LoadFirearm(Action|Reaction)
Чет не сходится...

2024-07-27 13:36 UTC, ch1-zha commented on game/src/main/java/com/vdn/lampbearer/entites/item/projectile/revolver/DefaultRevolverRound.java
> +        GameBlock stoneBlock = GameBlockFactory.returnGameBlock(stoneType);
Переименовать `stoneType` и `stoneBlock`

2024-07-27 13:36 UTC, ch1-zha commented on game/src/main/java/com/vdn/lampbearer/entites/item/projectile/revolver/SignalRevolverRound.java
> +        GameBlock stoneBlock = GameBlockFactory.returnGameBlock(stoneType);
Переименовать `stoneType` и `stoneBlock`

2024-07-27 13:38 UTC, RDaniil commented on game/src/main/java/com/vdn/lampbearer/action/reactions/LoadOneInFirearmReaction.java
> +        }
Согласен, обычно тоже так пишу

2024-07-28 08:27 UTC, ch1-zha approved these changes

2024-07-28 08:56 UTC, merged